### ISSUE TITLE
mvn clean test fail with Errors

### ISSUE THREAD

**Issue by 50028** [nuagenetworks/java-bambou#20]
Hello, 

"mvn clean test" returns a lot of errors. 

testStartSession(net.nuagenetworks.bambou.RestSessionTest)  Time elapsed: 0 sec  <<< FAILURE!
java.lang.AssertionError:
  Unexpected method call RestOperations.exchange("http://vsd/api/v2/root", GET, <{Content-Type=[application/json], X-Nuage-Organization=[martin], Authorization=[XREST bWFydGluOm1hcnRpbg==]}>, class [B):
    RestOperations.exchange("http://vsd/api/v2_1/root", GET, <any>, class [B): expected: 1, actual: 0
        at org.easymock.internal.MockInvocationHandler.invoke(MockInvocationHandler.java:44)
        at org.easymock.internal.ObjectMethodsFilter.invoke(ObjectMethodsFilter.java:94)
        at com.sun.proxy.$Proxy23.exchange(Unknown Source)
        at net.nuagenetworks.bambou.service.RestClientService.sendRequest(RestClientService.java:134)
        at net.nuagenetworks.bambou.service.RestClientService.sendRequest(RestClientService.java:109)
        at net.nuagenetworks.bambou.RestSession.sendRequestWithRetry(RestSession.java:393)
        at net.nuagenetworks.bambou.RestObject.fetch(RestObject.java:262)
        at net.nuagenetworks.bambou.RestSession.fetch(RestSession.java:275)
        at net.nuagenetworks.bambou.RestSession.authenticate(RestSession.java:436)
        at net.nuagenetworks.bambou.RestSession.start(RestSession.java:170)
        at net.nuagenetworks.bambou.RestSessionTest.startSession(RestSessionTest.java:170)
        at net.nuagenetworks.bambou.RestSessionTest.startSession(RestSessionTest.java:147)
        at net.nuagenetworks.bambou.RestSessionTest.testStartSession(RestSessionTest.java:79)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
        at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
        at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:254)
        at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:89)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
        at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:193)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

testStartSessionWithWrongCredentials(net.nuagenetworks.bambou.RestSessionTest)  Time elapsed: 0 sec  <<< FAILURE!
java.lang.AssertionError:
  Unexpected method call RestOperations.exchange("http://vsd/api/v2/root", GET, <{Content-Type=[application/json], X-Nuage-Organization=[martin], Authorization=[XREST bWFydGluOm1hcnRpbg==]}>, class [B):
    RestOperations.exchange("http://vsd/api/v2_1/root", GET, <any>, class [B): expected: 1, actual: 0
        at org.easymock.internal.MockInvocationHandler.invoke(MockInvocationHandler.java:44)
        at org.easymock.internal.ObjectMethodsFilter.invoke(ObjectMethodsFilter.java:94)
        at com.sun.proxy.$Proxy23.exchange(Unknown Source)
        at net.nuagenetworks.bambou.service.RestClientService.sendRequest(RestClientService.java:134)
        at net.nuagenetworks.bambou.service.RestClientService.sendRequest(RestClientService.java:109)
        at net.nuagenetworks.bambou.RestSession.sendRequestWithRetry(RestSession.java:393)
        at net.nuagenetworks.bambou.RestObject.fetch(RestObject.java:262)
        at net.nuagenetworks.bambou.RestSession.fetch(RestSession.java:275)
        at net.nuagenetworks.bambou.RestSession.authenticate(RestSession.java:436)
        at net.nuagenetworks.bambou.RestSession.start(RestSession.java:170)
        at net.nuagenetworks.bambou.RestSessionTest.startSession(RestSessionTest.java:170)
        at net.nuagenetworks.bambou.RestSessionTest.testStartSessionWithWrongCredentials(RestSessionTest.java:90)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
        at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
        at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:254)
        at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:89)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
        at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:193)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

Running net.nuagenetworks.bambou.RestUtilsTest
Jõn. 29, 2020 8:12:27 PM org.springframework.test.context.support.DefaultTestContextBootstrapper getDefaultTestExecutionListenerClassNames
INFO: Loaded default TestExecutionListener class names from location [META-INF/spring.factories]: [org.springframework.test.context.web.ServletTestExecutionListener, org.springframework.test.context.support.DirtiesContextBeforeModesTestExecutionListener, org.springframework.test.context.support.DependencyInjectionTestExecutionListener, org.springframework.test.context.support.DirtiesContextTestExecutionListener, org.springframework.test.context.transaction.TransactionalTestExecutionListener, org.springframework.test.context.jdbc.SqlScriptsTestExecutionListener]
Jõn. 29, 2020 8:12:27 PM org.springframework.test.context.support.DefaultTestContextBootstrapper instantiateListeners
INFO: Could not instantiate TestExecutionListener [org.springframework.test.context.web.ServletTestExecutionListener]. Specify custom listener classes or make the default listener classes (and their required dependencies) available. Offending class: [javax/servlet/ServletContext]
Jõn. 29, 2020 8:12:27 PM org.springframework.test.context.support.DefaultTestContextBootstrapper instantiateListeners
INFO: Could not instantiate TestExecutionListener [org.springframework.test.context.transaction.TransactionalTestExecutionListener]. Specify custom listener classes or make the default listener classes (and their required dependencies) available. Offending class: [org/springframework/transaction/interceptor/TransactionAttributeSource]
Jõn. 29, 2020 8:12:27 PM org.springframework.test.context.support.DefaultTestContextBootstrapper instantiateListeners
INFO: Could not instantiate TestExecutionListener [org.springframework.test.context.jdbc.SqlScriptsTestExecutionListener]. Specify custom listener classes or make the default listener classes (and their required dependencies) available. Offending class: [org/springframework/transaction/interceptor/TransactionAttribute]
Jõn. 29, 2020 8:12:27 PM org.springframework.test.context.support.DefaultTestContextBootstrapper getTestExecutionListeners
INFO: Using TestExecutionListeners: [org.springframework.test.context.support.DirtiesContextBeforeModesTestExecutionListener@3a320ade, org.springframework.test.context.support.DependencyInjectionTestExecutionListener@64beebb7, org.springframework.test.context.support.DirtiesContextTestExecutionListener@7813cb11]
Tests run: 3, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.016 sec <<< FAILURE!
testToJson(net.nuagenetworks.bambou.RestUtilsTest)  Time elapsed: 0 sec  <<< ERROR!
java.lang.NullPointerException
        at net.nuagenetworks.bambou.RestUtilsTest.testToJson(RestUtilsTest.java:104)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
        at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
        at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:254)
        at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:89)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
        at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:193)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

Results :

Failed tests:   testGoodKeyAndGoodCertificate(net.nuagenetworks.bambou.DynamicKeystoreGeneratorTest): RSA private key length expected:<46> but was:<1323>
  testFetchRemovedChild(net.nuagenetworks.bambou.RestFetcherTest): (..)
  testFetchWithHeaders(net.nuagenetworks.bambou.RestFetcherTest): (..)
  testGetFirst(net.nuagenetworks.bambou.RestFetcherTest): (..)
  testGet(net.nuagenetworks.bambou.RestFetcherTest): (..)
  testCount(net.nuagenetworks.bambou.RestFetcherTest): (..)
  testFetch(net.nuagenetworks.bambou.RestFetcherTest): (..)
  testFetchWith401Response(net.nuagenetworks.bambou.RestFetcherTest): (..)
  testGet2(net.nuagenetworks.bambou.RestFetcherTest): (..)
  testFetchNullContent(net.nuagenetworks.bambou.RestFetcherTest): (..)
  testCountWithHeaders(net.nuagenetworks.bambou.RestFetcherTest): (..)
  testGetWithHeaders(net.nuagenetworks.bambou.RestFetcherTest): (..)
  testFetchNoContent(net.nuagenetworks.bambou.RestFetcherTest): (..)
  testGetFirstWithHeaders(net.nuagenetworks.bambou.RestFetcherTest): (..)
  testFetchNoContent2(net.nuagenetworks.bambou.RestFetcherTest): (..)
  testFetchAddedChild(net.nuagenetworks.bambou.RestFetcherTest): (..)
  testAssignObjects(net.nuagenetworks.bambou.RestObjectTest): (..)
  testUnassignAllObjects(net.nuagenetworks.bambou.RestObjectTest): (..)
  testCreateChildObjectWith409Response(net.nuagenetworks.bambou.RestObjectTest): (..)
  testInstantiateChildObject(net.nuagenetworks.bambou.RestObjectTest): (..)
  testFetchObject(net.nuagenetworks.bambou.RestObjectTest): (..)
  testDeleteObject(net.nuagenetworks.bambou.RestObjectTest): (..)
  testSaveObject(net.nuagenetworks.bambou.RestObjectTest): (..)
  testCreateChildObject(net.nuagenetworks.bambou.RestObjectTest): (..)
  testFetchObjectWith401Response(net.nuagenetworks.bambou.RestObjectTest): (..)
  testCreateChildObjectWith201AndMultipleObjectsInResponse(net.nuagenetworks.bambou.RestObjectTest): (..)
  testPushCenterWith400Response(net.nuagenetworks.bambou.RestPushCenterTest): (..)
  testFetchObject(net.nuagenetworks.bambou.RestRootObjectTest): (..)
  testSaveObject(net.nuagenetworks.bambou.RestRootObjectTest): (..)
  testResetSession(net.nuagenetworks.bambou.RestSessionTest): (..)
  testStartSession(net.nuagenetworks.bambou.RestSessionTest): (..)
  testStartSessionWithWrongCredentials(net.nuagenetworks.bambou.RestSessionTest): (..)

Tests in error:
  testErrorResponseNoContent(net.nuagenetworks.bambou.RestClientServiceTest)
  testToJson(net.nuagenetworks.bambou.RestUtilsTest)

Tests run: 51, Failures: 32, Errors: 2, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  9.347 s

Br,
Martin

**Comment by pdumais** [comment]
tests have not been maintained for a while. We'll fix it

**Comment by 50028** [comment]
Great. Thank you very much!
